# VNE-GENERATED: ORDERED_ASS_RENPY_V1
# SOURCE: Accepted OrderedASS
# DO NOT EDIT: regenerated by the VNE OrderedASS export workflow.
# generated by tools/vne_to_renpy/ordered_ass_project_exporter.py
# reading_mode: classic_vn
# scene_count: 2

# accepted_ass: mfzxgx3tmnpww2lsmfpwq2lemrsw4x3qojxwe3dfnvptambrl53dc version=1 content_hash=df8bc151c385a070d3b2a6636eed342b9d51e837469aebaa671d0090657f7e70 scene_label=vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_start

# OrderedASS scene sc_kira_hidden_problem_001
# reading_mode: classic_vn

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_start:
    jump vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_mnug62ldmvpwg4c7ge

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_mnug62ldmvpwg4c7ge:
    narrator "Кира чувствует, что Андрей что-то недоговаривает. Как она поступит?"
    menu:
        "Кира говорит прямо: она не будет давить, но его молчание касается и её.":
            jump vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrr

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrr:
    pass

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrs:
    narrator "Кира медленно снимает пальто. Пальцы на секунду задерживаются на вешалке. Она касается шеи, быстро убирает руку и только тогда поворачивается к Андрею."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrt:
    kira "Я не молчу. Просто не хочу сейчас спрашивать. Если тебе есть что сказать — скажешь сам."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yru:
    andrey "Я не хотел тебя втягивать, пока сам не разберусь. Это не про тебя."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrv:
    pass

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrw:
    narrator "Кира медленно выпрямляется и убирает руку со стола на колени, сцепляя пальцы в замок — не от злости, а чтобы не потянуться к нему."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrx:
    kira "Не про меня. Понятно."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yry:
    andrey "Кира, я не хотел сказать, что ты для меня посторонняя. Я просто боялся, что, если расскажу сейчас, ты начнёшь решать эту проблему вместе со мной. А я пока даже не понимаю, что именно произошло."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrz:
    pass

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrrga:
    narrator "Кира опускает плечи, медленно выдыхает и садится чуть ближе, но не касается Андрея."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrrge:
    kira "Я не прошу тебя всё рассказать сейчас. Но когда ты молчишь, это всё равно касается меня. Просто помни об этом."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_end:
    return

# accepted_ass: mfzxgx3tmnpww2lsmfpxs33hmfpwqylmnrpxoylsnv2xaxzqgayv65rr version=1 content_hash=c27491900abf097a3113e6200b1d6335ea39b3b08818c5bc1533bc4784bd40e5 scene_label=vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_start

# OrderedASS scene sc_kira_yoga_hall_warmup_001
# reading_mode: classic_vn

label vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_start:
    jump vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_entry_nzqxe4tboruxmzk7gaydc

label vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_entry_nzqxe4tboruxmzk7gaydc:
    narrator "Кира разминается на беговой дорожке в зале для йоги."

label vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_end:
    return
