# VNE-GENERATED: ORDERED_ASS_RENPY_V1
# SOURCE: Accepted OrderedASS
# DO NOT EDIT: regenerated by the VNE OrderedASS export workflow.
# generated by tools/vne_to_renpy/ordered_ass_project_exporter.py
# reading_mode: classic_vn
# scene_count: 1

# accepted_ass: mfzxgx3tmnpww2lsmfpxs33hmfpwqylmnrpxoylsnv2xaxzqgayv65rr version=1 content_hash=c27491900abf097a3113e6200b1d6335ea39b3b08818c5bc1533bc4784bd40e5 scene_label=vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_start

# OrderedASS scene sc_kira_yoga_hall_warmup_001
# reading_mode: classic_vn

label vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_start:
    jump vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_entry_nzqxe4tboruxmzk7gaydc

label vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_entry_nzqxe4tboruxmzk7gaydc:
    narrator "Кира разминается на беговой дорожке в зале для йоги."

label vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_end:
    return
