# VNE-GENERATED: ORDERED_ASS_RENPY_V1
# SOURCE: Accepted OrderedASS
# DO NOT EDIT: regenerated by the VNE OrderedASS export workflow.
# generated by tools/vne_to_renpy/ordered_ass_project_exporter.py
# reading_mode: classic_vn
# scene_count: 3

# accepted_ass: mfzxgx3tmnpww2lsmfpwq2lemrsw4x3qojxwe3dfnvptambrl53dc version=1 content_hash=df8bc151c385a070d3b2a6636eed342b9d51e837469aebaa671d0090657f7e70 scene_label=vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_start

# OrderedASS scene sc_kira_hidden_problem_001
# reading_mode: classic_vn

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_start:
    jump vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_mnug62ldmvpwg4c7ge

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_mnug62ldmvpwg4c7ge:
    narrator "Кира чувствует, что Андрей что-то недоговаривает. Как она поступит?"
    menu:
        "Кира говорит прямо: она не будет давить, но его молчание касается и её.":
            jump vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrr

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrr:
    pass

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrs:
    narrator "Кира медленно снимает пальто. Пальцы на секунду задерживаются на вешалке. Она касается шеи, быстро убирает руку и только тогда поворачивается к Андрею."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrt:
    kira "Я не молчу. Просто не хочу сейчас спрашивать. Если тебе есть что сказать — скажешь сам."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yru:
    andrey "Я не хотел тебя втягивать, пока сам не разберусь. Это не про тебя."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrv:
    pass

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrw:
    narrator "Кира медленно выпрямляется и убирает руку со стола на колени, сцепляя пальцы в замок — не от злости, а чтобы не потянуться к нему."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrx:
    kira "Не про меня. Понятно."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yry:
    andrey "Кира, я не хотел сказать, что ты для меня посторонняя. Я просто боялся, что, если расскажу сейчас, ты начнёшь решать эту проблему вместе со мной. А я пока даже не понимаю, что именно произошло."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrz:
    pass

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrrga:
    narrator "Кира опускает плечи, медленно выдыхает и садится чуть ближе, но не касается Андрея."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_entry_gfqv6yrrge:
    kira "Я не прошу тебя всё рассказать сейчас. Но когда ты молчишь, это всё равно касается меня. Просто помни об этом."

label vne_scene_onrv623jojqv62djmrsgk3s7obzg6ytmmvwv6mbqge_end:
    return

# accepted_ass: mfzxgx3tmnpww2lsmfpxgzlsm5sxsx3nmvzxgylhmvpwcz3bnfxf6mbqgfpxmmi version=1 content_hash=29175b557598a696db562c8154a2bb52eaee9df71929c2dac5fed0456dcffbd9 scene_label=vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_start

# OrderedASS scene sc_kira_sergey_message_again_001
# reading_mode: classic_vn

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_start:
    jump vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_muyq

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_muyq:
    narrator "Телефон загорается новым сообщением от Сергея. Утренний разговор с Яковым ещё не успел стать привычкой."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_mnug62ldmvpwg4c7ge:
    narrator "Телефон загорается новым сообщением от Сергея. Утренний разговор с Яковым ещё не успел стать привычкой. Что делает Кира?"
    menu:
        "Показывает сообщение Якову сразу. Прозрачность прежде реакции.":
            jump vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfqv6yrr
        "Сначала читает сама. Просит одну минуту, прежде чем делиться.":
            jump vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrf6yrr
        "Не отвечает пока. Отказывается быть сразу втянутой в чужую срочность.":
            jump vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrv6yrr

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfqv6yrr:
    narrator "Показывает сообщение Якову сразу. Прозрачность прежде реакции."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfqv6yrs:
    kira "Он написал."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfqv6yrt:
    kira "Я показываю тебе это до ответа. Не потому что прошу разрешения. Потому что не хочу тайны."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfqv6yru:
    yakov "Ты показываешь мне это до ответа?"

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfqv6yrv:
    yakov "Тогда я рядом. Но отвечать будешь ты. Я не буду читать за тебя и не буду решать вместо тебя."
    jump vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_end

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrf6yrr:
    narrator "Сначала читает сама. Просит одну минуту, прежде чем делиться."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrf6yrs:
    kira "Я прочитаю сначала сама. Одну минуту."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrf6yrt:
    kira "Мне нужно понять, что я чувствую, прежде чем объяснять это тебе."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrf6yru:
    yakov "Я хочу спросить, почему не сразу. Но я подожду."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrf6yrv:
    yakov "Только не исчезай в этом одна."
    jump vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_end

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrv6yrr:
    narrator "Не отвечает пока. Отказывается быть сразу втянутой в чужую срочность."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrv6yrs:
    kira "Я не буду отвечать сейчас."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrv6yrt:
    kira "Не потому что боюсь. Потому что не хочу, чтобы его боль снова стала моим расписанием."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrv6yru:
    yakov "Тогда пусть сообщение подождёт. А мы — нет."

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_entry_gfrv6yrv:
    yakov "Ты имеешь право выбирать свой темп."
    jump vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_end

label vne_scene_onrv623jojqv643fojtwk6k7nvsxg43bm5sv6ylhmfuw4xzqgayq_end:
    return

# accepted_ass: mfzxgx3tmnpww2lsmfpxs33hmfpwqylmnrpxoylsnv2xaxzqgayv65rs version=2 content_hash=70fcb6edc7b217178acfad13f7210f8f833c413840f7e91103688d98971136fa scene_label=vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_start

# OrderedASS scene sc_kira_yoga_hall_warmup_001
# reading_mode: classic_vn

label vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_start:
    jump vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_entry_nzqxe4tboruxmzk7gaydc

label vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_entry_nzqxe4tboruxmzk7gaydc:
    narrator "Кира разминается на беговой дорожке в йога-зале."

label vne_scene_onrv623jojqv66lpm5qv62dbnrwf653bojwxk4c7gaydc_end:
    return
