# AUTO-GENERATED playable RenPy scene from VNE Scenario Schema V2 JSON.
# generated by tools/renpy_v2_playable_exporter.py
# source scene id: SC_017
# source: scenarios/SCENARIO_017_SERGEY_WRITES_AGAIN.v2.json
# source SHA256: 0a12c4622eb41764f85a102e53e70c63d96c4e2c385b76020b3a277d01b8bba0
# do not edit manually; regenerate from JSON source.

default v2_flags = set()
default v2_completed_scenes = set()
default v2_levels = {}
default v2_relationships = {}

label sc_017_v2_start:

    narrator "Сергей пишет снова"
    # beat_id: e1
    narrator "Телефон загорается новым сообщением от Сергея. Утренний разговор с Яковым ещё не успел стать привычкой."

    narrator "Телефон загорается новым сообщением от Сергея. Утренний разговор с Яковым ещё не успел стать привычкой. Что делает Кира?"

    menu:
        "Показывает сообщение Якову сразу. Прозрачность прежде реакции.":
            jump sc_017_v2_1a
        "Сначала читает сама. Просит одну минуту, прежде чем делиться.":
            jump sc_017_v2_1b
        "Не отвечает пока. Отказывается быть сразу втянутой в чужую срочность.":
            jump sc_017_v2_1c

label sc_017_v2_1a:

    # beat_id: 1A-b1
    narrator "[Кира action] Показывает сообщение Якову сразу. Прозрачность прежде реакции."
    # beat_id: 1A-b2
    narrator "Кира: Он написал."
    # beat_id: 1A-b3
    narrator "Кира: Я показываю тебе это до ответа. Не потому что прошу разрешения. Потому что не хочу тайны."
    # beat_id: 1A-b4
    narrator "Яков: Ты показываешь мне это до ответа?"
    # beat_id: 1A-b5
    narrator "Яков: Тогда я рядом. Но отвечать будешь ты. Я не буду читать за тебя и не буду решать вместо тебя."

    # effects
    $ v2_flags.add("kira_shows_message_immediately")
    $ v2_flags.add("yakov_stays_beside_not_over")
    $ v2_flags.add("transparency_strengthened")
    $ v2_flags.add("sc_017_1a")
    $ v2_levels["kira"] = "U5-выбор"
    $ v2_completed_scenes.add("SC_017")
    $ v2_flags.add("sc_017_complete")
    $ v2_completed_scenes.add("sc_017_complete")

    jump sc_017_v2_end

label sc_017_v2_1b:

    # beat_id: 1B-b1
    narrator "[Кира action] Сначала читает сама. Просит одну минуту, прежде чем делиться."
    # beat_id: 1B-b2
    narrator "Кира: Я прочитаю сначала сама. Одну минуту."
    # beat_id: 1B-b3
    narrator "Кира: Мне нужно понять, что я чувствую, прежде чем объяснять это тебе."
    # beat_id: 1B-b4
    narrator "Яков: Я хочу спросить, почему не сразу. Но я подожду."
    # beat_id: 1B-b5
    narrator "Яков: Только не исчезай в этом одна."

    # effects
    $ v2_flags.add("kira_reads_first")
    $ v2_flags.add("yakov_waits_without_pressure")
    $ v2_flags.add("boundary_under_stress")
    $ v2_flags.add("sc_017_1b")
    $ v2_levels["kira"] = "U5-выбор"
    $ v2_completed_scenes.add("SC_017")
    $ v2_flags.add("sc_017_complete")
    $ v2_completed_scenes.add("sc_017_complete")

    jump sc_017_v2_end

label sc_017_v2_1c:

    # beat_id: 1C-b1
    narrator "[Кира action] Не отвечает пока. Отказывается быть сразу втянутой в чужую срочность."
    # beat_id: 1C-b2
    narrator "Кира: Я не буду отвечать сейчас."
    # beat_id: 1C-b3
    narrator "Кира: Не потому что боюсь. Потому что не хочу, чтобы его боль снова стала моим расписанием."
    # beat_id: 1C-b4
    narrator "Яков: Тогда пусть сообщение подождёт. А мы — нет."
    # beat_id: 1C-b5
    narrator "Яков: Ты имеешь право выбирать свой темп."

    # effects
    $ v2_flags.add("kira_delays_answer")
    $ v2_flags.add("sergey_message_waits")
    $ v2_flags.add("kira_refuses_urgency")
    $ v2_flags.add("sc_017_1c")
    $ v2_levels["kira"] = "U5-выбор"
    $ v2_completed_scenes.add("SC_017")
    $ v2_flags.add("sc_017_complete")
    $ v2_completed_scenes.add("sc_017_complete")

    jump sc_017_v2_end

label sc_017_v2_end:

    return
