#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Character Lab Application Service v1 -- application-layer error model.

A thin, UI-agnostic facade over ``services.character_canon_bridge`` and the
local session model. Mirrors ``services.editor_application.errors``: expected
failures map into a stable, structured category instead of surfacing a raw
traceback to the UI boundary.
"""

from __future__ import annotations

OK = "OK"
NOT_FOUND = "NOT_FOUND"
INVALID_INPUT = "INVALID_INPUT"
CANON_UNAVAILABLE = "CANON_UNAVAILABLE"
INTERNAL_ERROR = "INTERNAL_ERROR"
CRP_VALIDATION_FAILED = "CRP_VALIDATION_FAILED"
AUTHORING_UNAVAILABLE = "AUTHORING_UNAVAILABLE"
AUTHORING_ALREADY_EXISTS = "AUTHORING_ALREADY_EXISTS"
AUTHORING_NOT_FOUND = "AUTHORING_NOT_FOUND"
AUTHORING_NOT_EDITABLE = "AUTHORING_NOT_EDITABLE"
AUTHORING_VALIDATION_FAILED = "AUTHORING_VALIDATION_FAILED"
AUTHORING_PERSISTENCE_FAILED = "AUTHORING_PERSISTENCE_FAILED"
IMMUTABLE_PERSISTENCE_FAILED = "IMMUTABLE_PERSISTENCE_FAILED"
IMPORT_SOURCE_UNAVAILABLE = "IMPORT_SOURCE_UNAVAILABLE"
IMPORT_REQUIRES_AUTHORING_COMPLETION = "IMPORT_REQUIRES_AUTHORING_COMPLETION"
AUTHORING_INVALID_LIFECYCLE_TRANSITION = "AUTHORING_INVALID_LIFECYCLE_TRANSITION"
AUTHORING_STALE_REVISION = "AUTHORING_STALE_REVISION"
AUTHORING_STALE_SNAPSHOT = "AUTHORING_STALE_SNAPSHOT"
DERIVATION_SOURCE_NOT_APPROVED = "DERIVATION_SOURCE_NOT_APPROVED"
PUBLICATION_NOT_APPROVED = "PUBLICATION_NOT_APPROVED"
PUBLICATION_STALE_REVISION = "PUBLICATION_STALE_REVISION"
PUBLICATION_STALE_SNAPSHOT = "PUBLICATION_STALE_SNAPSHOT"
PUBLICATION_SOURCE_CORRUPT = "PUBLICATION_SOURCE_CORRUPT"
PUBLICATION_VALIDATION_FAILED = "PUBLICATION_VALIDATION_FAILED"
PUBLICATION_PACKAGE_COLLISION = "PUBLICATION_PACKAGE_COLLISION"
PUBLICATION_STORAGE_FAILED = "PUBLICATION_STORAGE_FAILED"

ERROR_CODES = (
    OK,
    NOT_FOUND,
    INVALID_INPUT,
    CANON_UNAVAILABLE,
    INTERNAL_ERROR,
    CRP_VALIDATION_FAILED,
    AUTHORING_UNAVAILABLE,
    AUTHORING_ALREADY_EXISTS,
    AUTHORING_NOT_FOUND,
    AUTHORING_NOT_EDITABLE,
    AUTHORING_VALIDATION_FAILED,
    AUTHORING_PERSISTENCE_FAILED,
    IMMUTABLE_PERSISTENCE_FAILED,
    IMPORT_SOURCE_UNAVAILABLE,
    IMPORT_REQUIRES_AUTHORING_COMPLETION,
    AUTHORING_INVALID_LIFECYCLE_TRANSITION,
    AUTHORING_STALE_REVISION,
    AUTHORING_STALE_SNAPSHOT,
    DERIVATION_SOURCE_NOT_APPROVED,
    PUBLICATION_NOT_APPROVED,
    PUBLICATION_STALE_REVISION,
    PUBLICATION_STALE_SNAPSHOT,
    PUBLICATION_SOURCE_CORRUPT,
    PUBLICATION_VALIDATION_FAILED,
    PUBLICATION_PACKAGE_COLLISION,
    PUBLICATION_STORAGE_FAILED,
)


class CharacterLabApplicationError(Exception):
    """Bounded application-layer exception carrying a stable ``code``."""

    def __init__(
        self,
        code: str,
        message: str,
        *,
        details: dict[str, object] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = dict(details or {})
