#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OrderedASS canonical publication mechanism v1.

Publishes an already-PREPARED and already-LINTED ``OrderedProjectCandidate`` to
the FIXED canonical generated path (``novel/game/ordered_ass_generated.rpy``)
using same-directory atomic replacement, with strict ownership/path/symlink
containment guards and post-write SHA-256 verification.

Boundary:

- The publisher never builds a candidate, never renders, never resolves assets,
  and never invokes the Ren'Py SDK. It promotes an exact, immutable,
  hash-bound, successfully-linted candidate only.
- ``prepare_ordered_candidate_for_canonical_publication`` swaps ONLY the
  temporary project-candidate first line for the permanent ownership preamble
  and recomputes the source hash. It is the ONLY transformation between the
  TEMP candidate and the published bytes; nothing is transformed after lint.
- The fixed destination is derived solely from ``repo_root``; there is no
  arbitrary output path and no production write outside a caller-supplied
  ``repo_root`` (tests must use temporary repository fixtures only).
"""

from __future__ import annotations

import hashlib
import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .ordered_ass_candidate_lint import CandidateLintResult
from .ordered_ass_project_exporter import (
    ORDERED_ASS_CANDIDATE_FILENAME,
    OrderedProjectCandidate,
)

__all__ = [
    "prepare_ordered_candidate_for_canonical_publication",
    "publish_ordered_project_candidate",
    "OrderedCanonicalPublishResult",
    "OrderedCanonicalPublishError",
    "CANONICAL_ORDERED_ASS_RELATIVE_PATH",
    "ORDERED_ASS_GENERATED_OWNERSHIP_MARKER",
]

# Fixed permanent canonical generated path (repo-root-relative).
CANONICAL_ORDERED_ASS_RELATIVE_PATH = "novel/game/ordered_ass_generated.rpy"

# Authoritative ownership marker (exact first line of an owned generated file).
ORDERED_ASS_GENERATED_OWNERSHIP_MARKER = "# VNE-GENERATED: ORDERED_ASS_RENPY_V1"

# The temporary project-candidate first line replaced during preparation.
_TEMP_FIRST_LINE = "# AUTO-GENERATED OrderedASS Ren'Py project candidate."

_OWNERSHIP_PREAMBLE = (
    "# VNE-GENERATED: ORDERED_ASS_RENPY_V1\n"
    "# SOURCE: Accepted OrderedASS\n"
    "# DO NOT EDIT: regenerated by the VNE OrderedASS export workflow."
)

_SHA256_RE = re.compile(r"[0-9a-f]{64}\Z")


class OrderedCanonicalPublishError(Exception):
    """Raised on any canonical publication failure. Fails closed."""


@dataclass(frozen=True)
class OrderedCanonicalPublishResult:
    """Immutable result of a successful canonical publication."""

    output_path: Path
    source_sha256: str
    bytes_written: int
    replaced_existing: bool
    changed: bool


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def prepare_ordered_candidate_for_canonical_publication(
    candidate: OrderedProjectCandidate,
) -> OrderedProjectCandidate:
    """Transform the TEMP project candidate into publication-ready bytes.

    Replaces ONLY the expected temporary first line with the exact three-line
    permanent ownership preamble; all other source bytes are unchanged. Does NOT
    rerender, rebuild semantics, resolve assets, or call the renderer. Recomputes
    ``source_sha256`` over the exact new source bytes.
    """
    if not isinstance(candidate, OrderedProjectCandidate):
        raise OrderedCanonicalPublishError("candidate must be an OrderedProjectCandidate")
    if not candidate.source.startswith(_TEMP_FIRST_LINE + "\n"):
        raise OrderedCanonicalPublishError(
            "candidate is missing the expected temporary first line"
        )
    prepared_source = _OWNERSHIP_PREAMBLE + candidate.source[len(_TEMP_FIRST_LINE):]
    prepared_sha = _sha256_bytes(prepared_source.encode("utf-8"))
    return OrderedProjectCandidate(
        source=prepared_source,
        source_sha256=prepared_sha,
        scene_ids=candidate.scene_ids,
        ass_ids=candidate.ass_ids,
        reading_mode=candidate.reading_mode,
        candidate_filename=candidate.candidate_filename,
    )


def _validate_candidate(candidate: OrderedProjectCandidate) -> None:
    if not isinstance(candidate, OrderedProjectCandidate):
        raise OrderedCanonicalPublishError("candidate must be an OrderedProjectCandidate")
    if candidate.candidate_filename != ORDERED_ASS_CANDIDATE_FILENAME:
        raise OrderedCanonicalPublishError("candidate has an unexpected candidate_filename")
    if not isinstance(candidate.source_sha256, str) or _SHA256_RE.fullmatch(candidate.source_sha256) is None:
        raise OrderedCanonicalPublishError("candidate.source_sha256 must be 64 lowercase hex")
    recomputed = _sha256_bytes(candidate.source.encode("utf-8"))
    if recomputed != candidate.source_sha256:
        raise OrderedCanonicalPublishError("candidate source hash does not match its bytes")


def _validate_lint_result(
    candidate: OrderedProjectCandidate,
    lint_result: CandidateLintResult,
) -> None:
    if not isinstance(lint_result, CandidateLintResult):
        raise OrderedCanonicalPublishError("lint_result must be a CandidateLintResult")
    if lint_result.passed is not True:
        raise OrderedCanonicalPublishError("lint_result.passed is not True")
    if lint_result.returncode != 0:
        raise OrderedCanonicalPublishError("lint_result.returncode is not 0")
    if lint_result.temp_cleaned is not True:
        raise OrderedCanonicalPublishError("lint_result.temp_cleaned is not True")
    if not lint_result.command:
        raise OrderedCanonicalPublishError("lint_result.command is empty")
    if lint_result.candidate_filename != candidate.candidate_filename:
        raise OrderedCanonicalPublishError("lint_result.candidate_filename does not match candidate")
    if lint_result.candidate_source_sha256 != candidate.source_sha256:
        raise OrderedCanonicalPublishError("lint proof hash does not match candidate source hash")


def _resolve_destination(repo_root: Path) -> tuple[Path, Path]:
    """Return (destination, game_dir) after containment/link validation."""
    novel = repo_root / "novel"
    game = novel / "game"
    destination = game / "ordered_ass_generated.rpy"

    for component in (novel, game):
        if component.is_symlink():
            raise OrderedCanonicalPublishError(
                "{} is a symlink/junction; refusing to publish".format(component)
            )

    game_resolved = game.resolve()
    if destination.parent.resolve() != game_resolved:
        raise OrderedCanonicalPublishError("destination escapes the game directory")

    if destination.is_symlink():
        raise OrderedCanonicalPublishError("destination is a symlink")

    return destination, game


def _validate_repo_root(repo_root: Path) -> None:
    if not isinstance(repo_root, Path):
        raise OrderedCanonicalPublishError("repo_root must be a Path")
    if not repo_root.is_absolute():
        raise OrderedCanonicalPublishError("repo_root must be absolute")
    if not repo_root.exists():
        raise OrderedCanonicalPublishError("repo_root does not exist")
    if not repo_root.is_dir():
        raise OrderedCanonicalPublishError("repo_root is not a directory")
    if not (repo_root / "novel").exists():
        raise OrderedCanonicalPublishError("repo_root/novel does not exist")
    if not (repo_root / "novel" / "game").exists():
        raise OrderedCanonicalPublishError("repo_root/novel/game does not exist")


def _check_existing_destination(destination: Path) -> bytes | None:
    """Return existing destination bytes if owned, None if absent, else raise."""
    if not destination.exists():
        return None
    if destination.is_symlink():
        raise OrderedCanonicalPublishError("destination is a symlink")
    if not destination.is_file():
        raise OrderedCanonicalPublishError("destination is not a regular file")
    try:
        text = destination.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError) as exc:
        raise OrderedCanonicalPublishError("destination is not readable UTF-8") from exc
    if text == "":
        raise OrderedCanonicalPublishError("destination is empty")
    first_line = text.split("\n", 1)[0]
    if first_line != ORDERED_ASS_GENERATED_OWNERSHIP_MARKER:
        raise OrderedCanonicalPublishError("destination has wrong ownership marker")
    return destination.read_bytes()


def _atomic_write(destination: Path, game_dir: Path, data: bytes, source_sha256: str) -> None:
    """Atomically publish exact bytes via a same-directory staged temp file."""
    try:
        fd, tmp = tempfile.mkstemp(
            prefix=".ordered_ass_generated.", suffix=".tmp", dir=str(game_dir)
        )
    except OSError as exc:
        raise OrderedCanonicalPublishError(
            "failed to create staged temp file: {}".format(exc)
        ) from exc
    tmp_path = Path(tmp)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(data)
        staged_hash = _sha256_bytes(tmp_path.read_bytes())
        if staged_hash != source_sha256:
            raise OrderedCanonicalPublishError("staged temp file hash mismatch")
        os.replace(str(tmp_path), str(destination))
    except OrderedCanonicalPublishError:
        _cleanup_temp(tmp_path)
        raise
    except BaseException as exc:
        _cleanup_temp(tmp_path)
        raise OrderedCanonicalPublishError(
            "atomic publication failed: {}".format(exc)
        ) from exc


def _cleanup_temp(tmp_path: Path) -> None:
    try:
        if tmp_path.exists():
            tmp_path.unlink()
    except OSError:
        pass


def publish_ordered_project_candidate(
    candidate: OrderedProjectCandidate,
    lint_result: CandidateLintResult,
    *,
    repo_root: Path,
) -> OrderedCanonicalPublishResult:
    """Publish a PREPARED + LINTED candidate to the fixed canonical path.

    Validates the candidate self-hash and the hash-bound successful lint proof
    (Candidate A proof cannot authorize Candidate B), enforces ownership and
    path/symlink containment guards, and atomically writes the exact linted
    bytes. Never invokes the SDK, never builds the candidate, never takes an
    arbitrary output path.
    """
    _validate_candidate(candidate)
    _validate_lint_result(candidate, lint_result)
    _validate_repo_root(repo_root)

    destination, game_dir = _resolve_destination(repo_root)
    candidate_bytes = candidate.source.encode("utf-8")

    existing = _check_existing_destination(destination)
    if existing is not None:
        if _sha256_bytes(existing) == candidate.source_sha256:
            # identical owned destination -> deterministic no-op
            return OrderedCanonicalPublishResult(
                output_path=destination,
                source_sha256=candidate.source_sha256,
                bytes_written=0,
                replaced_existing=False,
                changed=False,
            )
        _atomic_write(destination, game_dir, candidate_bytes, candidate.source_sha256)
        _verify_destination(destination, candidate.source_sha256)
        return OrderedCanonicalPublishResult(
            output_path=destination,
            source_sha256=candidate.source_sha256,
            bytes_written=len(candidate_bytes),
            replaced_existing=True,
            changed=True,
        )

    # first publication
    _atomic_write(destination, game_dir, candidate_bytes, candidate.source_sha256)
    _verify_destination(destination, candidate.source_sha256)
    return OrderedCanonicalPublishResult(
        output_path=destination,
        source_sha256=candidate.source_sha256,
        bytes_written=len(candidate_bytes),
        replaced_existing=False,
        changed=True,
    )


def _verify_destination(destination: Path, expected_sha256: str) -> None:
    actual = _sha256_bytes(destination.read_bytes())
    if actual != expected_sha256:
        raise OrderedCanonicalPublishError(
            "post-publish destination hash mismatch (expected {}, actual {})".format(
                expected_sha256, actual
            )
        )
