Файл: 08_INDEX.json

```json
{
  "id": "kira",
  "name": "Кира",
  "version": "2.1.0",
  "schema_version": "1.0.0",
  "default_level": "U2-A",
  "default_ag_level": 1,
  "compatible_scenarios": [
    "sauna_quartet",
    "sauna_trio",
    "promenade",
    "evening_walk",
    "shy_girl_initiation",
    "cafe_date",
    "home_visit"
  ],
  "modules": {
    "core/IDENTITY.json": { "version": "1.0.0", "required": true },
    "psychology/BASE.json": { "version": "1.2.0", "required": true },
    "psychology/AROUSAL.json": { "version": "1.0.0", "required": false },
    "psychology/PLASTICITY.json": { "version": "1.0.0", "required": false },
    "psychology/ODSC.json": { "version": "1.0.0", "required": false },
    "psychology/ATTACHMENT.json": { "version": "1.0.0", "required": false },
    "psychology/TACTICS.json": { "version": "1.0.0", "required": false },
    "psychology/DEFENSE_MECHANISMS.json": { "version": "1.0.0", "required": false },
    "psychology/VALUE_SYSTEM.json": { "version": "1.0.0", "required": false },
    "psychology/ATTACHMENT_STYLE_DYNAMIC.json": { "version": "1.0.0", "required": false },
    "psychology/AFFECT_REGULATION.json": { "version": "1.0.0", "required": false },
    "psychology/IFS_PARTS.json": { "version": "1.0.0", "required": false },
    "psychology/COGNITIVE_DISTORTIONS.json": { "version": "1.0.0", "required": false },
    "physiology/AROUSAL_SIGNATURES.json": { "version": "1.0.0", "required": false },
    "physiology/CORTICAL_ACTIVATION.json": { "version": "1.0.0", "required": false },
    "physiology/MICROEXPRESSIONS.json": { "version": "1.0.0", "required": false },
    "physiology/EROGENOUS_MAP.json": { "version": "1.0.0", "required": false },
    "sexology/RESPONSE_CYCLE.json": { "version": "1.0.0", "required": false },
    "sexology/EROTIC_SCRIPTS.json": { "version": "1.0.0", "required": false },
    "sexology/DYSPHORIA_AND_SHAME.json": { "version": "1.0.0", "required": false },
    "sexology/FANTASY_VS_REALITY.json": { "version": "1.0.0", "required": false },
    "levels/U1-A.json": { "version": "1.0.0" },
    "levels/U1-B.json": { "version": "1.0.0" },
    "levels/U2-A.json": { "version": "1.0.0" },
    "levels/U2-B.json": { "version": "1.0.0" },
    "levels/U3-A.json": { "version": "1.0.0" },
    "levels/U3-B.json": { "version": "1.0.0" },
    "levels/U4-A.json": { "version": "1.0.0" },
    "levels/U4-B.json": { "version": "1.0.0" },
    "levels/U5-A.json": { "version": "1.0.0" },
    "levels/U5-B.json": { "version": "1.0.0" },
    "levels/U6-A.json": { "version": "1.0.0" },
    "levels/U6-B.json": { "version": "1.0.0" },
    "levels/U7-A.json": { "version": "1.0.0" },
    "levels/U7-B.json": { "version": "1.0.0" },
    "relationships/MATRIX.json": { "version": "1.1.0" },
    "dynamics/RIVALRY_TRIANGLE.json": { "version": "1.0.0", "required": false },
    "dynamics/CHARACTER_GROWTH_PATH.json": { "version": "1.0.0", "required": false },
    "visual/PROMPT_BASE.json": { "version": "1.0.0" },
    "visual/LIGHTING_MAP.json": { "version": "1.0.0" },
    "visual/GENERATION_HISTORY.json": { "version": "1.0.0" },
    "memory/TRUST.json": { "version": "1.0.0" },
    "memory/ATTRACTION.json": { "version": "1.0.0" },
    "memory/HISTORY.json": { "version": "1.0.0" },
    "memory/FLAGS.json": { "version": "1.0.0" },
    "memory/emotional_anchors.json": { "version": "1.0.0", "required": false },
    "autonomous/ACTIVITIES.json": { "version": "1.0.0" },
    "autonomous/TEMPLATES.json": { "version": "1.0.0" },
    "meta/ATTRIBUTION_BIAS.json": { "version": "1.0.0", "required": false },
    "meta/UNRELIABLE_NARRATOR.json": { "version": "1.0.0", "required": false },
    "meta/COHERENCE_VETO.json": { "version": "1.0.0", "required": false },
    "environment/SENSORY_PROCESSING.json": { "version": "1.0.0", "required": false },
    "environment/SPATIAL_BEHAVIOR.json": { "version": "1.0.0", "required": false },
    "evolution/AROUSAL_AS_MOTIVATION.json": { "version": "1.0.0", "required": false },
    "attachment/BEHAVIORAL_SYSTEMS.json": { "version": "1.0.0", "required": false },
    "sexual_scripts/EROTIC_SCRIPTS.json": { "version": "1.0.0", "required": false },
    "trauma_ptsd/THREE_LEVELS.json": { "version": "1.0.0", "required": false },
    "safety/PROTOCOL.json": { "version": "1.0.0", "required": true }
  },
  "dependencies": {
    "persona_schema": "v3_2_VOYAGE.json",
    "state_template": "STATE_TEMPLATE_v2.json",
    "session_finalize": "session_finalize.py v2.1+"
  }
}
```

Файл готов к сохранению под именем 08_INDEX.json.