#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Focused tests for the OrderedASS canonical publication mechanism."""

from __future__ import annotations

import hashlib
import inspect
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from services.ass import build_ordered_ass  # noqa: E402
from services.scene_body import (  # noqa: E402
    AUTHORING_SCHEMA_VERSION,
    ChoiceEntry,
    ChoiceOption,
    ChoiceTarget,
    Participant,
    SceneBody,
    TextEntry,
    VisualChangeEvent,
)
from tools.vne_to_renpy import (  # noqa: E402
    CANONICAL_ORDERED_ASS_RELATIVE_PATH,
    ORDERED_ASS_CANDIDATE_FILENAME,
    ORDERED_ASS_GENERATED_OWNERSHIP_MARKER,
    CandidateLintResult,
    OrderedCanonicalPublishError,
    OrderedCanonicalPublishResult,
    OrderedProjectCandidate,
    build_ordered_project_candidate,
    prepare_ordered_candidate_for_canonical_publication,
    publish_ordered_project_candidate,
)

TEMP_FIRST_LINE = "# AUTO-GENERATED OrderedASS Ren'Py project candidate."
OWNERSHIP_PREAMBLE = (
    "# VNE-GENERATED: ORDERED_ASS_RENPY_V1\n"
    "# SOURCE: Accepted OrderedASS\n"
    "# DO NOT EDIT: regenerated by the VNE OrderedASS export workflow."
)


def _temp_candidate(scene_id="SC_900", ass_id="ass_900", text="Hello.") -> OrderedProjectCandidate:
    body = SceneBody(
        authoring_schema_version=AUTHORING_SCHEMA_VERSION,
        scene_id=scene_id,
        location_id="yoga_hall",
        participants=(Participant(character_id="KIRA", role="protagonist", present=True),),
        content_rating="PG",
        entries=(TextEntry(entry_id="e1", presentation="NARRATIVE", text=text),),
    )
    ass = build_ordered_ass(body, ass_id=ass_id, version=1, source_ref="x", source_hash="0" * 64)
    tmp = Path(tempfile.mkdtemp(prefix="vne_pub_"))
    reg = tmp / "registry.json"
    reg.write_text('{"assets": []}', encoding="utf-8")
    return build_ordered_project_candidate(
        (ass,), reading_mode="classic_vn", character_symbols={},
        registry_path=reg, repo_root=tmp,
    )


def _prepared_candidate(scene_id="SC_900", ass_id="ass_900", text="Hello.") -> OrderedProjectCandidate:
    return prepare_ordered_candidate_for_canonical_publication(
        _temp_candidate(scene_id=scene_id, ass_id=ass_id, text=text)
    )


def _lint(candidate: OrderedProjectCandidate) -> CandidateLintResult:
    return CandidateLintResult(
        candidate_filename=candidate.candidate_filename,
        candidate_source_sha256=candidate.source_sha256,
        command=("python", "renpy.py", "novel", "lint", "--error-code"),
        returncode=0, stdout="", stderr="", passed=True, temp_cleaned=True,
    )


def _repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    (repo / "novel" / "game").mkdir(parents=True)
    (repo / "novel" / "game" / "scenes_v2_generated.rpy").write_text(
        "label sc_017_v2_start:\n    return\n", encoding="utf-8"
    )
    (repo / "novel" / "game" / "script.rpy").write_text(
        "label start:\n    return\n", encoding="utf-8"
    )
    return repo


def _canonical_path(repo: Path) -> Path:
    return repo / "novel" / "game" / "ordered_ass_generated.rpy"


# ---------------------------------------------------------------------------
# Preparation
# ---------------------------------------------------------------------------

def test_preparation_requires_temporary_marker():
    bad = OrderedProjectCandidate(
        source="# WRONG first line\n# something\n",
        source_sha256=hashlib.sha256(b"# WRONG first line\n# something\n").hexdigest(),
        scene_ids=("SC_900",), ass_ids=("ass_900",),
        reading_mode="classic_vn", candidate_filename=ORDERED_ASS_CANDIDATE_FILENAME,
    )
    with pytest.raises(OrderedCanonicalPublishError):
        prepare_ordered_candidate_for_canonical_publication(bad)


def test_preparation_ownership_preamble_exact():
    c = _prepared_candidate()
    assert c.source.startswith(OWNERSHIP_PREAMBLE + "\n")


def test_preparation_replaces_only_first_line():
    temp = _temp_candidate()
    prepared = prepare_ordered_candidate_for_canonical_publication(temp)
    expected = OWNERSHIP_PREAMBLE + temp.source[len(TEMP_FIRST_LINE):]
    assert prepared.source == expected


def test_preparation_preserves_metadata():
    c = _prepared_candidate(scene_id="SC_900", ass_id="ass_900")
    assert c.scene_ids == ("SC_900",)
    assert c.ass_ids == ("ass_900",)
    assert c.reading_mode == "classic_vn"
    assert c.candidate_filename == ORDERED_ASS_CANDIDATE_FILENAME


def test_preparation_recomputes_hash():
    c = _prepared_candidate()
    assert c.source_sha256 == hashlib.sha256(c.source.encode("utf-8")).hexdigest()


def test_preparation_deterministic():
    a = _prepared_candidate()
    b = _prepared_candidate()
    assert a.source == b.source
    assert a.source_sha256 == b.source_sha256


def test_preparation_does_not_rerender():
    a = _prepared_candidate(text="Hello.")
    b = _prepared_candidate(text="Goodbye.")
    assert a.source != b.source


# ---------------------------------------------------------------------------
# Promotion gate / hash proof
# ---------------------------------------------------------------------------

def _publish(candidate, lint_result, repo):
    return publish_ordered_project_candidate(candidate, lint_result, repo_root=repo)


def test_first_publication_creates(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    r = _publish(c, _lint(c), repo)
    assert isinstance(r, OrderedCanonicalPublishResult)
    assert r.changed is True
    assert r.replaced_existing is False
    assert r.bytes_written == len(c.source.encode("utf-8"))
    assert _canonical_path(repo).read_bytes() == c.source.encode("utf-8")


def test_identical_destination_noop(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    _publish(c, _lint(c), repo)
    r2 = _publish(c, _lint(c), repo)
    assert r2.changed is False
    assert r2.replaced_existing is False
    assert r2.bytes_written == 0


def test_different_owned_destination_replaces(tmp_path):
    repo = _repo(tmp_path)
    c1 = _prepared_candidate(text="One.")
    _publish(c1, _lint(c1), repo)
    c2 = _prepared_candidate(text="Two.")
    r2 = _publish(c2, _lint(c2), repo)
    assert r2.changed is True
    assert r2.replaced_existing is True
    assert _canonical_path(repo).read_bytes() == c2.source.encode("utf-8")


def test_unowned_existing_file_rejected(tmp_path):
    repo = _repo(tmp_path)
    _canonical_path(repo).write_text("# someone's file\n", encoding="utf-8")
    c = _prepared_candidate()
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), repo)


def test_empty_existing_file_rejected(tmp_path):
    repo = _repo(tmp_path)
    _canonical_path(repo).write_text("", encoding="utf-8")
    c = _prepared_candidate()
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), repo)


def test_invalid_utf8_existing_file_rejected(tmp_path):
    repo = _repo(tmp_path)
    _canonical_path(repo).write_bytes(b"\xff\xfe\x00")
    c = _prepared_candidate()
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), repo)


def test_destination_directory_rejected(tmp_path):
    repo = _repo(tmp_path)
    _canonical_path(repo).mkdir()
    c = _prepared_candidate()
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), repo)


def test_destination_symlink_rejected(tmp_path):
    repo = _repo(tmp_path)
    target = tmp_path / "target.rpy"
    target.write_text("# x\n", encoding="utf-8")
    try:
        _canonical_path(repo).symlink_to(target)
    except (OSError, NotImplementedError):
        pytest.skip("symlinks not supported on this platform")
    c = _prepared_candidate()
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), repo)


# ---------------------------------------------------------------------------
# Promotion gate (hash proof binding)
# ---------------------------------------------------------------------------

def test_candidate_a_proof_cannot_authorize_candidate_b(tmp_path):
    repo = _repo(tmp_path)
    a = _prepared_candidate(text="One.")
    b = _prepared_candidate(text="Two.")
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(b, _lint(a), repo)  # A's proof, B's candidate


def test_mismatched_lint_hash_rejected(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    bad_lint = CandidateLintResult(
        candidate_filename=c.candidate_filename,
        candidate_source_sha256="0" * 64,  # wrong hash
        command=("python", "renpy.py", "novel", "lint", "--error-code"),
        returncode=0, stdout="", stderr="", passed=True, temp_cleaned=True,
    )
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, bad_lint, repo)


def test_wrong_candidate_filename_rejected(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    bad_lint = _lint(c)
    bad_lint = CandidateLintResult(
        candidate_filename="other.rpy",
        candidate_source_sha256=c.source_sha256,
        command=bad_lint.command, returncode=0, stdout="", stderr="",
        passed=True, temp_cleaned=True,
    )
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, bad_lint, repo)


def test_failed_lint_rejected(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    bad = CandidateLintResult(
        candidate_filename=c.candidate_filename,
        candidate_source_sha256=c.source_sha256,
        command=("python",), returncode=0, stdout="", stderr="",
        passed=False, temp_cleaned=True,
    )
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, bad, repo)


def test_nonzero_returncode_rejected(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    bad = CandidateLintResult(
        candidate_filename=c.candidate_filename,
        candidate_source_sha256=c.source_sha256,
        command=("python",), returncode=1, stdout="", stderr="",
        passed=True, temp_cleaned=True,
    )
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, bad, repo)


def test_uncleaned_lint_rejected(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    bad = CandidateLintResult(
        candidate_filename=c.candidate_filename,
        candidate_source_sha256=c.source_sha256,
        command=("python",), returncode=0, stdout="", stderr="",
        passed=True, temp_cleaned=False,
    )
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, bad, repo)


def test_empty_command_rejected(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    bad = CandidateLintResult(
        candidate_filename=c.candidate_filename,
        candidate_source_sha256=c.source_sha256,
        command=(), returncode=0, stdout="", stderr="",
        passed=True, temp_cleaned=True,
    )
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, bad, repo)


def test_publisher_has_no_arbitrary_output_param():
    sig = inspect.signature(publish_ordered_project_candidate)
    params = set(sig.parameters)
    assert "output_path" not in params
    assert "output" not in params
    assert "repo_root" in params


# ---------------------------------------------------------------------------
# Path / containment
# ---------------------------------------------------------------------------

def test_repo_root_non_absolute_rejected(tmp_path):
    c = _prepared_candidate()
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), Path("relative/repo"))


def test_missing_repo_rejected(tmp_path):
    c = _prepared_candidate()
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), tmp_path / "nope")


def test_missing_novel_rejected(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    c = _prepared_candidate()
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), repo)


def test_missing_game_rejected(tmp_path):
    repo = tmp_path / "repo"
    (repo / "novel").mkdir(parents=True)
    c = _prepared_candidate()
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), repo)


def test_fixed_canonical_path(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    r = _publish(c, _lint(c), repo)
    assert r.output_path == _canonical_path(repo)
    assert str(r.output_path.relative_to(repo)).replace("\\", "/") == CANONICAL_ORDERED_ASS_RELATIVE_PATH


# ---------------------------------------------------------------------------
# Atomicity / byte identity / coexistence
# ---------------------------------------------------------------------------

def test_same_directory_temp_used(tmp_path, monkeypatch):
    import tools.vne_to_renpy.ordered_ass_canonical_publisher as mod
    real_mkstemp = tempfile.mkstemp
    seen: list[str] = []

    def fake_mkstemp(*args, **kwargs):
        seen.append(kwargs.get("dir", ""))
        return real_mkstemp(*args, **kwargs)

    monkeypatch.setattr(mod.tempfile, "mkstemp", fake_mkstemp)
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    _publish(c, _lint(c), repo)
    assert seen
    assert all(Path(d).resolve() == (repo / "novel" / "game").resolve() for d in seen)


def test_replace_failure_leaves_old_destination_unchanged(tmp_path, monkeypatch):
    repo = _repo(tmp_path)
    c1 = _prepared_candidate(text="One.")
    _publish(c1, _lint(c1), repo)
    c2 = _prepared_candidate(text="Two.")

    def fake_replace(src, dst):
        raise OSError("injected replace failure")

    monkeypatch.setattr(os, "replace", fake_replace)
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c2, _lint(c2), repo)
    assert _canonical_path(repo).read_bytes() == c1.source.encode("utf-8")
    # no temp artifact left behind
    leftovers = list((repo / "novel" / "game").glob(".ordered_ass_generated.*.tmp"))
    assert leftovers == []


def test_replace_failure_on_first_publish_leaves_no_destination(tmp_path, monkeypatch):
    repo = _repo(tmp_path)
    c = _prepared_candidate()

    def fake_replace(src, dst):
        raise OSError("injected replace failure")

    monkeypatch.setattr(os, "replace", fake_replace)
    with pytest.raises(OrderedCanonicalPublishError):
        _publish(c, _lint(c), repo)
    assert not _canonical_path(repo).exists()
    leftovers = list((repo / "novel" / "game").glob(".ordered_ass_generated.*.tmp"))
    assert leftovers == []


def test_published_bytes_are_exact_and_lf(tmp_path):
    repo = _repo(tmp_path)
    c = _prepared_candidate()
    _publish(c, _lint(c), repo)
    published = _canonical_path(repo).read_bytes()
    assert published == c.source.encode("utf-8")
    assert b"\r\n" not in published
    assert published.endswith(b"\n")
    assert not published.endswith(b"\n\n")
    assert hashlib.sha256(published).hexdigest() == c.source_sha256
    assert b"2026" not in published  # no timestamp


def test_coexistence_v2_and_owner_files_unchanged(tmp_path):
    repo = _repo(tmp_path)
    v2 = repo / "novel" / "game" / "scenes_v2_generated.rpy"
    script = repo / "novel" / "game" / "script.rpy"
    v2_before = v2.read_bytes()
    script_before = script.read_bytes()
    c = _prepared_candidate()
    _publish(c, _lint(c), repo)
    assert v2.read_bytes() == v2_before
    assert script.read_bytes() == script_before


# ---------------------------------------------------------------------------
# Actual local Ren'Py SDK final-path proof (authorized; env-gated)
# ---------------------------------------------------------------------------

def test_actual_sdk_final_path_integration(tmp_path):
    sdk_raw = os.environ.get("VNE_TEST_RENPY_SDK_PATH")
    if not sdk_raw:
        pytest.skip("VNE_TEST_RENPY_SDK_PATH not set")
    sdk_path = Path(sdk_raw)

    from tools.renpy_static_validator import find_renpy_command
    from tools.vne_to_renpy import lint_ordered_ass_candidate

    # temp repository fixture: copy the real source novel in (read-only input)
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    shutil.copytree(_REPO_ROOT / "novel", repo_root / "novel")
    registry_path = _REPO_ROOT / "scenarios" / "visual_assets" / "ASSET_REGISTRY.json"

    def _scene(scene_id, ass_id, entries):
        body = SceneBody(
            authoring_schema_version=AUTHORING_SCHEMA_VERSION,
            scene_id=scene_id,
            location_id="yoga_hall",
            participants=(Participant(character_id="KIRA", role="protagonist", present=True),),
            content_rating="PG",
            entries=entries,
        )
        return build_ordered_ass(body, ass_id=ass_id, version=1, source_ref="x", source_hash="0" * 64)

    scene_a = _scene("SC_900", "ass_900", (
        TextEntry(entry_id="e1", presentation="NARRATIVE", text="Kira enters the yoga hall."),
        ChoiceEntry(entry_id="c1", prompt="Continue?", options=(
            ChoiceOption(option_id="o1", display_text="Continue",
                         target=ChoiceTarget(target_kind="SCENE", target_id="SC_901")),
        )),
        VisualChangeEvent(entry_id="v1", operation="SET", asset_id="kira_yoga_hall_pilot_image_01"),
    ))
    scene_b = _scene("SC_901", "ass_901", (
        TextEntry(entry_id="e1", presentation="NARRATIVE", text="Kira continues."),
        VisualChangeEvent(entry_id="v1", operation="CLEAR", asset_id=None),
    ))

    candidate = build_ordered_project_candidate(
        (scene_a, scene_b),
        reading_mode="classic_vn",
        character_symbols={},
        registry_path=registry_path,
        repo_root=repo_root,
    )
    prepared = prepare_ordered_candidate_for_canonical_publication(candidate)

    lint_result = lint_ordered_ass_candidate(
        prepared,
        source_novel_path=repo_root / "novel",
        sdk_path=sdk_path,
    )
    assert lint_result.passed is True

    publish_result = publish_ordered_project_candidate(
        prepared, lint_result, repo_root=repo_root
    )
    assert publish_result.changed is True

    canonical = repo_root / "novel" / "game" / "ordered_ass_generated.rpy"
    assert canonical.read_bytes() == prepared.source.encode("utf-8")
    assert hashlib.sha256(canonical.read_bytes()).hexdigest() == prepared.source_sha256
    assert (repo_root / "novel" / "game" / "scenes_v2_generated.rpy").exists()

    # run real SDK lint against the temp project with the final canonical file present
    command_info = find_renpy_command(sdk_path)
    assert command_info is not None
    python_exe, renpy_entry = command_info
    if renpy_entry == python_exe:
        cmd = [str(python_exe), str(repo_root / "novel"), "lint", "--error-code"]
    else:
        cmd = [str(python_exe), str(renpy_entry), str(repo_root / "novel"), "lint", "--error-code"]
    env = os.environ.copy()
    env["SDL_VIDEODRIVER"] = "dummy"
    env["SDL_AUDIODRIVER"] = "dummy"
    env["RENPY_PATH_TO_SAVES"] = str(tmp_path / "saves")
    completed = subprocess.run(
        cmd, capture_output=True, text=True, encoding="utf-8",
        errors="replace", env=env, timeout=300,
    )
    assert completed.returncode == 0, completed.stderr

    # real source novel unchanged
    assert not (_REPO_ROOT / "novel" / "game" / "ordered_ass_generated.rpy").exists()
