#!/usr/bin/env python3
"""Static validator for generated RenPy V2 playable artifacts (N5B)."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


GENERATED_RPY_REL = Path("novel/game/scenes_v2_generated.rpy")
SCRIPT_RPY_REL = Path("novel/game/script.rpy")
DEFINITIONS_RPY_REL = Path("novel/game/definitions.rpy")
OPTIONS_RPY_REL = Path("novel/game/options.rpy")
NOVEL_REL = Path("novel")

DEFAULT_SDK_PATH = Path("C:/DEV/Narrative/renpy-8.5.3-sdk")

REQUIRED_GENERATED_LABELS = [
    "sc_017_v2_start",
    "sc_017_v2_1a",
    "sc_017_v2_1b",
    "sc_017_v2_1c",
    "sc_017_v2_end",
]

FORBIDDEN_GENERATED_LABELS = [
    "sc_017_start",
    "sc_017_1a",
    "sc_017_1b",
    "sc_017_1c",
    "sc_017_1a_end",
    "sc_017_1b_end",
    "sc_017_1c_end",
]

REQUIRED_HANDAUTHORED_LABELS = [
    "sc_003_start",
    "sc_017_start",
    "sc_018_start",
]

REQUIRED_CONTENT_SNIPPETS = [
    "AUTO-GENERATED",
    "generated by tools/renpy_v2_playable_exporter.py",
    "source SHA256:",
    "menu:",
    "jump sc_017_v2_1a",
    "jump sc_017_v2_1b",
    "jump sc_017_v2_1c",
    "default v2_flags = set()",
    "default v2_completed_scenes = set()",
    "default v2_levels = {}",
    "default v2_relationships = {}",
    "sc_017_complete",
    "return",
]

REQUIRED_EXECUTABLE_EFFECTS = [
    "$ v2_flags.add",
    "$ v2_completed_scenes.add",
]


class ValidationError(Exception):
    """Expected validation failure with a user-facing message."""


class ValidatorResult:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def add_error(self, message: str) -> None:
        self.errors.append(message)

    def add_warning(self, message: str) -> None:
        self.warnings.append(message)

    def ok(self) -> bool:
        return not self.errors


def configure_encoding() -> None:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except Exception:
                pass


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def generated_rpy_path() -> Path:
    return repo_root() / GENERATED_RPY_REL


def script_rpy_path() -> Path:
    return repo_root() / SCRIPT_RPY_REL


def definitions_rpy_path() -> Path:
    return repo_root() / DEFINITIONS_RPY_REL


def options_rpy_path() -> Path:
    return repo_root() / OPTIONS_RPY_REL


def novel_path() -> Path:
    return repo_root() / NOVEL_REL


def file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def file_hashes(paths: list[Path]) -> dict[Path, str]:
    return {path: file_sha256(path) for path in paths}


def collect_labels(path: Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    return set(re.findall(r"^label\s+([A-Za-z0-9_]+)\s*:", text, flags=re.M))


def _check_file_exists(result: ValidatorResult, path: Path, name: str) -> bool:
    if not path.exists():
        result.add_error(f"{name} not found: {path}")
        return False
    return True


def check_generated_file_exists(result: ValidatorResult) -> None:
    _check_file_exists(result, generated_rpy_path(), "generated playable file")


def check_required_generated_labels(result: ValidatorResult) -> None:
    path = generated_rpy_path()
    if not path.exists():
        return
    labels = collect_labels(path)
    for label in REQUIRED_GENERATED_LABELS:
        if label not in labels:
            result.add_error(f"missing required generated label: {label}")


def check_forbidden_generated_labels(result: ValidatorResult) -> None:
    path = generated_rpy_path()
    if not path.exists():
        return
    labels = collect_labels(path)
    for label in FORBIDDEN_GENERATED_LABELS:
        if label in labels:
            result.add_error(
                f"generated file redefines hand-authored label: {label}"
            )


def check_required_content(result: ValidatorResult) -> None:
    path = generated_rpy_path()
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8")
    for snippet in REQUIRED_CONTENT_SNIPPETS:
        if snippet not in text:
            result.add_error(f"missing required content snippet: {snippet!r}")


def parse_generated_header(path: Path) -> tuple[str | None, str | None]:
    """Parse source path and SHA256 from generated .rpy header comments."""
    source_path: str | None = None
    source_sha: str | None = None
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return (None, None)
    for line in text.splitlines()[:50]:
        stripped = line.strip()
        if not stripped.startswith("#"):
            continue
        sha_match = re.match(
            r"^#\s*(?:[Ss]ource\s+)?[Ss][Hh][Aa]256\s*:\s*([0-9a-fA-F]+)$",
            stripped,
        )
        if sha_match and source_sha is None:
            source_sha = sha_match.group(1).lower()
            continue
        src_match = re.match(r"^#\s*[Ss]ource\s*:\s*(.+)$", stripped)
        if src_match and source_path is None:
            value = src_match.group(1).strip()
            lower = value.lower()
            if lower.startswith("scene id") or lower.startswith("sha256"):
                continue
            # Skip if value looks like a 64-char hex string without separators.
            if len(value) == 64 and all(c in "0123456789abcdef" for c in lower):
                continue
            source_path = value
    return (source_path, source_sha)


def resolve_source_path(source_header: str, repo_root_path: Path) -> Path:
    """Resolve a header source path relative to repo root or absolute."""
    raw = source_header.strip()
    if not raw:
        raise ValueError("empty source path")
    candidate = Path(raw)
    if candidate.is_absolute():
        return candidate.resolve()
    return (repo_root_path / candidate).resolve()


def check_generated_source_freshness(
    result: ValidatorResult,
    generated_path: Path | None = None,
    repo_root_path: Path | None = None,
) -> None:
    """Verify that the generated .rpy source SHA256 matches the current source JSON."""
    generated = generated_path or generated_rpy_path()
    root = repo_root_path or repo_root()
    if not generated.exists():
        return

    source_header, sha_header = parse_generated_header(generated)
    if source_header is None:
        result.add_error("generated file header missing source path")
        return
    if sha_header is None:
        result.add_error("generated file header missing source SHA256")
        return

    try:
        source_path = resolve_source_path(source_header, root)
    except Exception as exc:
        result.add_error(f"could not resolve source path {source_header!r}: {exc}")
        return

    if not source_path.exists():
        result.add_error(f"generated file source not found: {source_path}")
        return

    # Guard against relative paths that escape the repo root.
    if not source_path.is_absolute():
        try:
            if not source_path.is_relative_to(root.resolve()):
                result.add_error(f"source path escapes repo root: {source_path}")
                return
        except Exception:
            pass

    current_sha = file_sha256(source_path).lower()
    if current_sha != sha_header:
        result.add_error(
            f"generated file is stale: source SHA256 mismatch "
            f"(header={sha_header}, current={current_sha})"
        )


def check_executable_effects(result: ValidatorResult) -> None:
    path = generated_rpy_path()
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8")
    for snippet in REQUIRED_EXECUTABLE_EFFECTS:
        if snippet not in text:
            result.add_error(f"missing executable effect marker: {snippet!r}")
    if "sc_017_complete" not in text:
        result.add_error("missing executable completion flag: sc_017_complete")


def check_no_label_collisions(result: ValidatorResult) -> None:
    generated = generated_rpy_path()
    script = script_rpy_path()
    if not generated.exists() or not script.exists():
        return
    generated_labels = collect_labels(generated)
    script_labels = collect_labels(script)
    collisions = generated_labels & script_labels
    if collisions:
        result.add_error(
            f"generated labels collide with script.rpy: {sorted(collisions)}"
        )


def check_key_handauthored_labels(result: ValidatorResult) -> None:
    path = script_rpy_path()
    if not path.exists():
        result.add_error("script.rpy not found")
        return
    labels = collect_labels(path)
    for label in REQUIRED_HANDAUTHORED_LABELS:
        if label not in labels:
            result.add_error(f"missing required hand-authored label: {label}")


def run_structural_validation() -> ValidatorResult:
    result = ValidatorResult()
    check_generated_file_exists(result)
    check_required_generated_labels(result)
    check_forbidden_generated_labels(result)
    check_required_content(result)
    check_generated_source_freshness(result)
    check_executable_effects(result)
    check_no_label_collisions(result)
    check_key_handauthored_labels(result)
    return result


def protected_files() -> list[Path]:
    return [
        script_rpy_path(),
        definitions_rpy_path(),
        options_rpy_path(),
        generated_rpy_path(),
    ]


def resolve_sdk_path(sdk_path: Path | None) -> Path | None:
    if sdk_path is not None:
        if sdk_path.exists():
            return sdk_path
        return None

    env = os.environ.get("RENPY_SDK_PATH")
    if env:
        p = Path(env)
        if p.exists():
            return p

    if DEFAULT_SDK_PATH.exists():
        return DEFAULT_SDK_PATH

    return None


def find_renpy_command(sdk: Path) -> tuple[Path, Path] | None:
    """Return (python executable, renpy.py path) or None."""
    renpy_py = sdk / "renpy.py"
    embedded_python = sdk / "lib" / "py3-windows-x86_64" / "python.exe"
    if embedded_python.exists() and renpy_py.exists():
        return (embedded_python, renpy_py)

    if sys.executable and renpy_py.exists():
        return (Path(sys.executable), renpy_py)

    renpy_exe = sdk / "renpy.exe"
    if renpy_exe.exists():
        # Return executable as "python" and itself as "script" to signal exe mode.
        return (renpy_exe, renpy_exe)

    return None


def run_sdk_lint(sdk: Path, timeout: int = 120) -> tuple[int, str, str]:
    """Run RenPy lint against a temporary copy of the novel project."""
    python_exe, renpy_entry = find_renpy_command(sdk)
    if python_exe is None:
        raise ValidationError("could not find RenPy executable in SDK")

    with tempfile.TemporaryDirectory(prefix="vne_renpy_lint_") as tmp:
        temp_novel = Path(tmp) / "novel"
        shutil.copytree(novel_path(), temp_novel, dirs_exist_ok=True)

        env = os.environ.copy()
        env["SDL_VIDEODRIVER"] = "dummy"
        env["SDL_AUDIODRIVER"] = "dummy"
        env["RENPY_PATH_TO_SAVES"] = str(Path(tmp) / "saves")

        if renpy_entry == python_exe:
            # exe mode: renpy.exe <basedir> lint --error-code
            cmd = [str(python_exe), str(temp_novel), "lint", "--error-code"]
        else:
            # python mode: python.exe renpy.py <basedir> lint --error-code
            cmd = [str(python_exe), str(renpy_entry), str(temp_novel), "lint", "--error-code"]

        result = subprocess.run(
            cmd,
            cwd=repo_root(),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            env=env,
            timeout=timeout,
        )

        return result.returncode, result.stdout, result.stderr


def print_output(stdout: str, stderr: str) -> None:
    if stdout:
        print(stdout, end="" if stdout.endswith("\n") else "\n")
    if stderr:
        print(stderr, end="" if stderr.endswith("\n") else "\n", file=sys.stderr)


def cmd_validate_v2_generated(args: argparse.Namespace) -> int:
    protected = protected_files()
    before_hashes = file_hashes(protected)

    try:
        print("=== N5B STRUCTURAL VALIDATION ===")
        structural = run_structural_validation()
        for warning in structural.warnings:
            print(f"WARN: {warning}")
        if not structural.ok():
            for error in structural.errors:
                print(f"FAIL: {error}")
            return 1
        print("PASS: structural checks")

        sdk = resolve_sdk_path(args.sdk_path)
        run_sdk = not args.skip_sdk_lint

        if run_sdk:
            if sdk is None:
                message = "RenPy SDK not found"
                if args.require_sdk_lint:
                    print(f"FAIL: {message}")
                    return 1
                print(f"WARN: {message}; skipping SDK lint")
            else:
                print(f"=== N5B SDK LINT (temp copy) ===")
                print(f"SDK: {sdk}")
                exit_code, stdout, stderr = run_sdk_lint(sdk)
                print_output(stdout, stderr)
                if exit_code != 0:
                    print(f"FAIL: RenPy SDK lint exited with {exit_code}")
                    return 1
                print("PASS: RenPy SDK lint")

        after_hashes = file_hashes(protected)
        for path in protected:
            if before_hashes[path] != after_hashes[path]:
                print(
                    f"FAIL: protected file was modified during validation: {path}"
                )
                return 1
        print("PASS: protected files unchanged")

        print("=== N5B VALIDATION RESULT: PASS ===")
        return 0

    except ValidationError as exc:
        print(f"FAIL: {exc}")
        return 1
    except subprocess.TimeoutExpired:
        print("FAIL: RenPy SDK lint timed out")
        return 1
    except Exception as exc:
        print(f"FAIL: unexpected error: {exc}")
        return 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Static validator for generated RenPy V2 playable artifacts."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_validate = sub.add_parser(
        "validate-v2-generated",
        help="Validate the generated V2 RenPy scene",
    )
    p_validate.add_argument(
        "--skip-sdk-lint",
        action="store_true",
        default=False,
        help="Skip RenPy SDK lint and run structural checks only",
    )
    p_validate.add_argument(
        "--require-sdk-lint",
        action="store_true",
        default=False,
        help="Fail if RenPy SDK lint cannot be run",
    )
    p_validate.add_argument(
        "--sdk-path",
        type=Path,
        default=None,
        help="Path to RenPy SDK (default: C:/DEV/Narrative/renpy-8.5.3-sdk)",
    )
    p_validate.set_defaults(func=cmd_validate_v2_generated)

    return parser


def main() -> int:
    configure_encoding()
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
